### PR TITLE
Added an additional attributes map the to OAuthToken

### PR DESCRIPTION
**Pull request by kyleboon**

### CODE REVIEW

**Comment by kyleboon** [comment]
just a brain fart.

**Comment by jeff-blaisdell** [comment]
Rest looks good to me.  Fix that and I'll thumb.

**Comment by kyleboon** [comment]
Done @jeff-blaisdell - working on the service side work now

**Comment by kyleboon** [comment]
seems like a nice change. You just mean one copyOf there though right?

**Comment by jeff-blaisdell** [comment]
👍

**Pull request merged**
