### PR TITLE
nov-214 Fix warning log message that caused by null logging id

### PR DESCRIPTION
**Pull request by raymond-ti**
__JIRA Issue:__ [NOV-214](https://smartthings.atlassian.net/browse/NOV-214)

__Depends On:__ None

__Depended On By:__ None

__Developer(s):__ @raymond-ti  

__Details:__
- Log message "level=WARN , loggingId=, logger=o.asynchttpclient.RequestBuilderBase, message=Value was null, set to """ shown at warning level in Marconi and other services that use DropWizard. To resolve the issue, we can't add null header when building the request.

cc/ @lbredeso @Bijnagte @jeff-blaisdell @darksun @elventear @mailmahee

### CODE REVIEW

**Comment by elventear** [comment]
Under what circumstances is the logging id null?

**Comment by raymond-ti** [comment]
When correlation id is missing from MDC. To link all requests from different services together, correlation id is used to pass between services and the value will be stored in MDC. In Marconi case, the ID is not passed from Mobile client, so the value will be null, so warning message is shown.

**Comment by elventear** [comment]
Without being very familiar with this code, sounds that the correlation ID is optional. If that is the case, this code looks correct to me.

**Comment by jeff-blaisdell** [comment]
That's not quite correct @raymond-ti.  The loggingId doesn't depend on a calling service to pass in a correlationId.  If you've properly configured your Dropwizard app, it should either:
a) Use the correlationId on incoming request.
b) If no correlationId is present, generate a new UUID which would be set as loggingId.

That specific code lives here:
https://github.com/SmartThingsOSS/dropwizard-common/blob/master/dropwizard-logging/src/main/java/smartthings/dw/logging/LoggingFilter.java

Which is initialized upon invoking the following in your application's dw module:
```
install(new LoggingModule());
```

So I think the warning is good, as it probably means you have something misconfigured in your app.

**Comment by raymond-ti** [comment]
@jeff-blaisdell , thank you so much for the information. We are missing the logginModule in Marconi, I will add that to Marconi and close this PR.

**Pull request closed without merging**
